version: '3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
        container_name: elasticsearch
        ports:
            - "9200:9200"
    memcached:
        image: "memcached:1.6"
    mysql:
        image: "mysql:8.3"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3600:3600"
    app:
        build: apache
        depends_on:
            - elasticsearch
            - memcached
            - mysql
        ports:
            - "8080:80"
            - "4430:443"
        volumes:
            - "../../:/var/www/html/geekgigs"
