version: '3'
volumes:
    elasticsearch:
        driver: local
    kibana:
        driver: local
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
        container_name: elasticsearch
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
    kibana:
        image: docker.elastic.co/kibana/kibana:8.12.0
        container_name: kibana
        depends_on:
            - elasticsearch
        links:
            - elasticsearch
        environment:
            - SERVERNAME=kibana
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - ELASTICSEARCH_USERNAME=kibana
            - ELASTICSEARCH_PASSWORD=kibana
        volumes:
            - kibana:/usr/share/kibana/data
        ports:
            - "5601:5601"
#    memcached:
#        container_name: memcached
#        image: "memcached:1.6"
    mysql:
        container_name: mysql
        image: "mysql:8.3"
        command: --default-authentication-plugin=mysql_native_password --init-file=/data/application/init.sql
        volumes:
            - "../../docker/development/mysql/init.sql:/data/application/init.sql"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3600:3600"
    app:
        container_name: app
        build: apache
        depends_on:
#            - memcached
            - elasticsearch
            - mysql
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "../../:/var/www/html/geekgigs"
